### ISSUE TITLE
Ovcice!

### ISSUE THREAD

**Issue by northmirko** [mprinc/mcm_ionic#1]

**Comment by mprinc** [comment]
Ниси довољно објаснио који је проблем и како се рекреира ;) Затварамо случај

**Comment by northmirko** [comment]
Meeeeeeeee!

**Comment by mprinc** [comment]
Блеји колико хоћеш! Правила су стриктна, да се не помисли да је непотизам.
али можеш урадити PR (Pull Request) па ћемо га размотрити!
